#!/usr/bin/env ruby

# hint from here:
# http://stackoverflow.com/questions/6803344/rake-tasks-and-rails-initializers

root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
Dir.chdir(root)

require 'rubygems'
gem 'daemons'
require 'daemons'

options = {
    :dir_mode   => :normal,
    :dir        => File.join(root, 'log'),
    :log_output => true,
    :backtrace  => true,
    :multiple   => false
}

Daemons.run_proc("scheduler", options) do

  Dir.chdir(root)
  require(File.join(root, 'config', 'environment'))
  require 'rufus/scheduler'

  scheduler = Rufus::Scheduler.start_new

  scheduler.every '11m', :allow_overlapping => false, :first_in => '5m' do
    Mailreceiver::receive('mail_handler.yml')
  end

  scheduler.every '13m', :allow_overlapping => false, :first_in => '5m' do
    Mailreceiver::receive('mail_handler_help.yml')
  end

  scheduler.every '17m', :allow_overlapping => false, :first_in => '5m' do
    Mailreceiver::receive('mail_handler_cz.yml')
  end

end

